apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
  name: allow-ingress-red-colorpad.yml
  namespace: another
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          project: colorpad
  podSelector:
    matchLabels:
      color: red
  policyTypes:
  - Ingress
